### ISSUE TITLE
running ti_mds_cnn.py train mode (windows)

### ISSUE THREAD

**Issue by HAUKEYE1** [radar-lab/ti-mmwave-cnn#1]
Hi, I've downloaded the project at windows environment.
When running the training stage i get the following messaged.
please assist.
python ti_mds_cnn.py train mode
C:\Users\Gil.Albo\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2019-05-05 22:04:41.163752: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Loaded model from disk.
Traceback (most recent call last):
  File "ti_mds_cnn.py", line 127, in <module>
    mds_dl().main()
  File "ti_mds_cnn.py", line 124, in main
    self.model_predict()
  File "ti_mds_cnn.py", line 113, in model_predict
    test_data = np.genfromtxt(self.test_file, delimiter=',')
  File "C:\Users\Gil.Albo\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1737, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "C:\Users\Gil.Albo\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\Gil.Albo\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: ./output/test.csv not found.

**Comment by zrmaker** [comment]
Hi there,

This repo currently runs for the paper I published: https://ieeexplore.ieee.org/abstract/document/8585077

You may refer to paper to know deep on this repo. Data is not provided actually. So you need to collect data for yourself.

Leo
